// 前端 mock 商品資料，供商品列表、詳情與結帳流程使用。
import type { Product } from '../types'
import { assetPath } from '../utils/assetPath'

export const mockProducts: Product[] = [
  {
    id: 1,
    title: 'Aural X9 主動降噪耳罩耳機',
    category: '無線耳罩',
    price: 129,
    inventory: 18,
    rating: 4.9,
    description:
      '旗艦級主動降噪與沉浸式低頻表現，讓通勤、專注工作與深夜聆聽都更安靜。',
    features: ['40mm 動態單體', '主動降噪 ANC', '最長 42 小時續航'],
    image: assetPath('images/products/aural-x9.webp'),
    images: [assetPath('images/products/aural-x9.webp'), assetPath('images/products/aural-x9-2.webp')],
  },
  {
    id: 2,
    title: 'Echo Air Lite 真無線藍牙耳機',
    category: '真無線',
    price: 79,
    inventory: 34,
    rating: 4.7,
    description:
      '小巧輕盈的入耳式設計，適合日常通話、影音娛樂與運動隨行。',
    features: ['藍牙 5.4', '雙麥克風通話降噪', 'IPX5 防潑水'],
    image: assetPath('images/products/EchoAirLite.webp'),
    images: [
      assetPath('images/products/EchoAirLite.webp'),
      assetPath('images/products/EchoAirLite-2.webp'),
      assetPath('images/products/EchoAirLite-3.webp'),
    ],
  },
  {
    id: 3,
    title: 'Studio Pro 70 錄音室監聽耳機',
    category: '專業監聽',
    price: 159,
    inventory: 12,
    rating: 4.8,
    description:
      '中性聲音走向與寬廣音場，特別適合混音、剪輯與長時間監聽工作。',
    features: ['高解析監聽調音', '可替換耳罩', '可拆式音源線'],
    image: assetPath('images/products/studio-pro-70.webp'),
    images: [
      assetPath('images/products/studio-pro-70.webp'),
      assetPath('images/products/studio-pro-70-2.webp'),
      assetPath('images/products/studio-pro-70-3.webp'),
    ],
  },
  {
    id: 4,
    title: 'Bass Flow Max 運動頸掛藍牙耳機',
    category: '運動耳機',
    price: 69,
    inventory: 21,
    rating: 4.6,
    description:
      '穩固貼耳與節奏感十足的低頻調校，跑步與健身時依然有穩定表現。',
    features: ['磁吸收納', '低延遲模式', '14 小時播放'],
    image: assetPath('images/products/bass-flow-max.webp'),
    images: [
      assetPath('images/products/bass-flow-max.webp'),
      assetPath('images/products/bass-flow-max-2.webp'),
      assetPath('images/products/bass-flow-max-3.webp'),
    ],
  },
  {
    id: 5,
    title: 'Clarity Open 開放式氣傳導耳機',
    category: '開放式',
    price: 99,
    inventory: 26,
    rating: 4.5,
    description:
      '兼顧配戴舒適與環境感知，適合戶外騎行、辦公與長時間使用。',
    features: ['開放式音場', '雙裝置連線', '人體工學耳掛'],
    image: assetPath('images/products/clarity-open.webp'),
    images: [assetPath('images/products/clarity-open.webp'), assetPath('images/products/clarity-open-2.webp')],
  },
  {
    id: 6,
    title: 'Retro Wave 有線 Hi-Fi 耳機',
    category: '有線耳機',
    price: 59,
    inventory: 40,
    rating: 4.4,
    description:
      '為喜歡純粹聲音的人打造，保留有線音質細節與復古外型手感。',
    features: ['Hi-Res Audio', '3.5mm / 6.35mm 雙接頭', '鋁合金外殼'],
    image: assetPath('images/products/retro-wave.webp'),
    images: [assetPath('images/products/retro-wave.webp'),
      assetPath('images/products/retro-wave-2.webp'),
      assetPath('images/products/retro-wave-3.webp')]
  },
  {
    id: 7,
    title: 'Nova Silence X9 旅用主動降噪耳罩',
    category: '主動降噪',
    price: 149,
    inventory: 16,
    rating: 4.8,
    description:
      '專為長時間通勤與飛行打造，穩定降噪與柔軟耳罩設計，帶來沉浸且舒適的聆聽體驗。',
    features: ['智慧 ANC 調整', '環境聲快速切換', '快充 10 分鐘播放 5 小時'],
    image: assetPath('images/products/NovaSilenceX9.webp'),
    images: [
      assetPath('images/products/NovaSilenceX9.webp'),
      assetPath('images/products/NovaSilenceX9-2.webp'),
      assetPath('images/products/NovaSilenceX9-3.webp'),
      assetPath('images/products/NovaSilenceX9-4.webp'),
    ],
  },
  {
    id: 8,
    title: 'AirPulse Pro 真無線降噪耳機',
    category: '真無線',
    price: 119,
    inventory: 28,
    rating: 4.7,
    description:
      '輕量設計結合主動降噪，滿足通勤、會議與日常音樂需求的全方位耳機。',
    features: ['混合式 ANC', '三麥通話降噪', '最長 32 小時續航'],
    image: assetPath('images/products/AirPulsePro.webp'),
    images: [
      assetPath('images/products/AirPulsePro.webp'),
      assetPath('images/products/AirPulsePro-2.webp'),
      assetPath('images/products/AirPulsePro-3.webp'),
      assetPath('images/products/AirPulsePro-4.webp'),
    ],
  },
  {
    id: 9,
    title: 'RiftStrike GX 無線電競耳機',
    category: '電競耳機',
    price: 139,
    inventory: 14,
    rating: 4.9,
    description:
      '專為 FPS 玩家設計，提供低延遲連線與精準聲音定位，提升戰場反應速度。',
    features: ['2.4GHz 極低延遲', '可拆式降噪麥克風', '7.1 環繞音效'],
    image: assetPath('images/products/RiftStrikeGX.webp'),
    images: [
      assetPath('images/products/RiftStrikeGX.webp'),
      assetPath('images/products/RiftStrikeGX-2.webp'),
      assetPath('images/products/RiftStrikeGX-3.webp'),
    ],
  },
  {
    id: 10,
    title: 'OpenSense Air 開放式藍牙耳機',
    category: '開放式',
    price: 109,
    inventory: 22,
    rating: 4.5,
    description:
      '保留環境聲的開放式設計，適合長時間佩戴與需要感知周圍環境的場景。',
    features: ['氣傳導音場', '輕量耳掛', '雙設備快速切換'],
    image: assetPath('images/products/OpenSenseAir.webp'),
    images: [
      assetPath('images/products/OpenSenseAir.webp'),
      assetPath('images/products/OpenSenseAir-2.webp'),
      assetPath('images/products/OpenSenseAir-3.webp'),
    ],
  },
  {
    id: 11,
    title: 'Linear Studio 90 專業監聽耳機',
    category: '專業監聽',
    price: 189,
    inventory: 10,
    rating: 4.8,
    description:
      '低染色聲音表現，專為錄音與混音打造，提供穩定且精準的聲音還原。',
    features: ['封閉式監聽結構', '可換線設計', '高密度記憶耳墊'],
    image: assetPath('images/products/LinearStudio90-.webp'),
    images: [
      assetPath('images/products/LinearStudio90-.webp'),
      assetPath('images/products/LinearStudio90-2.webp'),
      assetPath('images/products/LinearStudio90-3.webp'),
      assetPath('images/products/LinearStudio90-4.webp'),
    ],
  },
  {
    id: 12,
    title: 'SprintBeat Flow 運動真無線耳機',
    category: '運動耳機',
    price: 89,
    inventory: 33,
    rating: 4.6,
    description:
      '穩固配戴與強化低頻，為跑步與健身提供持續節奏與動力。',
    features: ['IPX6 防水', '運動耳翼設計', '強化低頻模式'],
    image: assetPath('images/products/BassFlowMax.webp'),
    images: [
      assetPath('images/products/BassFlowMax.webp'),
      assetPath('images/products/BassFlowMax-2.webp'),
      assetPath('images/products/BassFlowMax-3.webp'),
    ],
  },
  {
    id: 13,
    title: 'Noir Silence 50 都會降噪耳罩',
    category: '主動降噪',
    price: 169,
    inventory: 13,
    rating: 4.7,
    description:
      '極簡外型搭配細膩降噪，適合城市通勤與專注工作使用。',
    features: ['多段降噪調節', '低壓耳罩設計', '多點連線'],
    image: assetPath('images/products/NoirSilence50.webp'),
    images: [
      assetPath('images/products/NoirSilence50.webp'),
      assetPath('images/products/NoirSilence50-2.webp'),
      assetPath('images/products/NoirSilence50-3.webp'),
    ],
  },
  {
    id: 14,
    title: 'AirMini Lite 真無線耳機',
    category: '真無線',
    price: 69,
    inventory: 42,
    rating: 4.4,
    description:
      '輕巧便攜設計，適合日常通勤與影音娛樂的入門選擇。',
    features: ['低延遲影音模式', '單耳使用', 'IPX4 防潑水'],
    image: assetPath('images/products/AirMiniLite.webp'),
    images: [
      assetPath('images/products/AirMiniLite.webp'),
      assetPath('images/products/AirMiniLite-2.webp'),
      assetPath('images/products/AirMiniLite-3.webp'),
    ],
  },
  {
    id: 15,
    title: 'Vortex Elite RGB 電競耳機',
    category: '電競耳機',
    price: 99,
    inventory: 25,
    rating: 4.6,
    description:
      '沉浸式音場與清晰語音，適合長時間遊戲與直播使用。',
    features: ['RGB 燈效', '降噪麥克風', '50mm 大單體'],
    image: assetPath('images/products/VortexEliteRGB.webp'),
    images: [
      assetPath('images/products/VortexEliteRGB.webp'),
      assetPath('images/products/VortexEliteRGB-2.webp'),
      assetPath('images/products/VortexEliteRGB-3.webp'),
    ],
  },
  {
    id: 16,
    title: 'OpenRun Pro 開放式運動耳機',
    category: '開放式',
    price: 129,
    inventory: 19,
    rating: 4.5,
    description:
      '結合開放音場與穩定耳掛，讓戶外運動更安全與舒適。',
    features: ['開放式設計', '抗風噪通話', 'IPX5 防汗'],
    image: assetPath('images/products/OpenRunPro.webp'),
    images: [
      assetPath('images/products/OpenRunPro.webp'),
      assetPath('images/products/OpenRunPro-2.webp'),
      assetPath('images/products/OpenRunPro-3.webp'),
    ],
  },
  {
    id: 17,
    title: 'Reference M1 高解析監聽耳機',
    category: '專業監聽',
    price: 209,
    inventory: 8,
    rating: 4.9,
    description:
      '高解析聲音細節，適合專業音訊工作與精準混音需求。',
    features: ['高解析單體', '開放式音場', '可更換耳罩'],
    image: assetPath('images/products/ReferenceM1.webp'),
    images: [
      assetPath('images/products/ReferenceM1.webp'),
      assetPath('images/products/ReferenceM1-2.webp'),
    ],
  },
  {
    id: 18,
    title: 'AquaFlow 頸掛式運動耳機',
    category: '運動耳機',
    price: 79,
    inventory: 31,
    rating: 4.5,
    description:
      '穩定頸掛設計與防水性能，適合高強度運動與戶外使用。',
    features: ['IPX7 防水', '頸掛穩定結構', '16 小時續航'],
    image: assetPath('images/products/AquaFlow.webp'),
    images: [
      assetPath('images/products/AquaFlow.webp'),
      assetPath('images/products/AquaFlow-2.webp'),
      assetPath('images/products/AquaFlow-3.webp'),
    ],
  },
]

